[package]
name = "mimalloc3"
version = "0.1.54"
authors = [
    "Octavian Oncescu <octavonce@gmail.com>",
    "Vincent Rouillé <vincent@speedy37.fr>",
    "Thom Chiovoloni <chiovolonit@gmail.com>",
    "Mnwa <mihan@panfilov.biz>",
]
edition = "2024"
repository = "https://github.com/purpleprotocol/mimalloc_rust"
keywords = ["mimalloc", "allocator", "encrypted-heap", "performance"]
categories = ["memory-management", "api-bindings"]
description = "Rust 2024 drop-in allocator backed by the latest stable mimalloc v3, with optional v2 support"
license = "MIT"
readme = "README.md"

[workspace]
members = [
    "libmimalloc-sys",
    "libmimalloc-sys/sys-test",
    "test-override-with-dylib",
]

[dependencies]
libmimalloc-sys3 = { path = "libmimalloc-sys", version = "0.1.51", default-features = false }

[features]
default = []
secure = ["libmimalloc-sys3/secure"]
override = ["libmimalloc-sys3/override"]
debug = ["libmimalloc-sys3/debug"]
debug_in_debug = ["libmimalloc-sys3/debug_in_debug"]
local_dynamic_tls = ["libmimalloc-sys3/local_dynamic_tls"]
nightly_allocator_api = ["extended"]
win_direct_tls = ["libmimalloc-sys3/win_direct_tls"]
no_thp = ["libmimalloc-sys3/no_thp"]
extended = ["libmimalloc-sys3/extended"]
v2 = ["libmimalloc-sys3/v2"]
