[package]
name = "libmimalloc-sys-test"
version = "0.1.0"
authors = ["Thom Chiovoloni <tchiovoloni@mozilla.com>"]
edition = "2024"
description = "Bindings test for libmimalloc-sys3"
license = "MIT"
publish = false

[dependencies]
libmimalloc-sys3 = { path = ".." }
libc = "0.2"

[build-dependencies]
ctest = "0.5"

[features]
secure = ["libmimalloc-sys3/secure"]
extended = ["libmimalloc-sys3/extended"]
v2 = ["libmimalloc-sys3/v2"]
